### ISSUE TITLE
[telegraf] No support for `[[inputs.postgresql_extensible.query]]`?

### ISSUE THREAD

**Issue by florianrusch** [influxdata/helm-charts#111]
Hi everybody,

currenty I'm migrating my local telegraf docker instance to a helm instance.
I'm currently using the input plugin `postgresql_extensible` with which I can define some queries in this format:

```toml
[[inputs.postgresql_extensible]]
  address = "..."

  [[inputs.postgresql_extensible.query]]
    script="/app/foobar.sql"
    version="1200"
    withdbname=false
    tagvalue="tenant"
    measurement="something"
```

This is my current yaml version of it:

```yaml
config:
  - inputs:
    - postgresql_extensible:
      address: "..."
      query:
        script: "/app/foobar.sql"
        version: "1200"
        withdbname: "false"
        tagvalue: "tenant"
        measurement: "something"
```

If I try to run this I'm getting this error message:

```
2020-06-18T12:10:31Z I! Starting Telegraf 1.14.4
2020-06-18T12:10:31Z I! Using config file: /etc/telegraf/telegraf.conf
2020-06-18T12:10:31Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 75: cannot unmarshal TOML table into postgresql_extensible.query (need struct or map)
```

This is the produced TOML at that possition:
```toml
[[inputs.postgresql_extensible]]
  address = "..."
  [inputs.postgresql_extensible.query]
    measurement = "something"
    script = "/app/foobar.sql"
    tagvalue = "tenant"
    version = "1200"
    withdbname = "false"
```

As you can see there is just one bracket pair (`[...query]`) and not two (`[[...query]]`).
I've looked into the `_helpers.tpl` and for me it looks like, that this use case isn't support currently.

Am I correct and does someone know a workaround or something?

**Comment by florianrusch** [comment]
Or is this a bug??

For the outputs there are two bracket pairs:
https://github.com/influxdata/helm-charts/blob/c0904994d655da1c78c800d5ddcb7feb578728c5/charts/telegraf/templates/_helpers.tpl#L137

And aso for the proccessors:
https://github.com/influxdata/helm-charts/blob/c0904994d655da1c78c800d5ddcb7feb578728c5/charts/telegraf/templates/_helpers.tpl#L321

But not for the input plugins:
https://github.com/influxdata/helm-charts/blob/c0904994d655da1c78c800d5ddcb7feb578728c5/charts/telegraf/templates/_helpers.tpl#L232

**Comment by rawkode** [comment]
Can you try

```
config:
  - inputs:
    - postgresql_extensible:
      address: "..."
      - query:
          script: "/app/foobar.sql"
          version: "1200"
          withdbname: "false"
          tagvalue: "tenant"
          measurement: "something"
```

**Comment by rawkode** [comment]
If this doesn't work, we'll provide a way to inject arbitrary configuration.

Unfortunately the code tries to handle too many cases right now and I think it's a mess.

**Comment by florianrusch** [comment]
@rawkode I don't think this is working. 😕

It's producing this toml:
```toml
[[inputs.postgresql_extensible]]
  address = "..."
  query = [
  ]
```

**Comment by florianrusch** [comment]
@rawkode btw. I've also found another bug and provided directly a pull request: https://github.com/influxdata/helm-charts/pull/110

**Comment by buroa** [comment]
I am also getting weird toml outputs from an SNMP field. I believe it has to do with arbitrary configuration.

```
  inputs:
    - snmp:
        agents:
          - udp://x.x.x.x:161
        timeout: 5s
        retries: 3
        version: 1
        community: public
        name: "ups"
        field:
          - oid: "1.3.6.1.4.1.3808.1.1.1.1.1.2.0"
            name: "hostname"
            is_tag: true
```

Produces this:

```
[[inputs.snmp]]
  agents = [
    "udp://x.x.x.x:161"
  ]
  community = "public"
  field = [
  ]
  name = "ups"
  retries = 3
  timeout = "5s"
  version = 1
```
