### ISSUE TITLE
Chronograf Chart Probes Incompatible with BASE_PATH & Ingress other than /

### ISSUE THREAD

**Issue by cpumanaz** [influxdata/helm-charts#113]
Using the updated configurable ingress path in the helm chart is great in conjunction with the BASE_PATH which tells  chronograf to serve from a sub-path, like `/chronograf`.  Unfortunately the probes do not support this leaving the user with a CrashLoopBackOff due to failure of the probes.

```
       livenessProbe:
          httpGet:
            path: /ping
            port: api
        readinessProbe:
          httpGet:
            path: /ping
            port: api
```

Recommendation is to add a chart value that will set both the env: for BASE_PATH, and the /{BASE_PATH}/ping  to the same base path, and everything will work great if you are using a proxy, or something like nginx-ingress.
