### ISSUE TITLE
[telegraf]: unable to pass `processor.converter.field` values

### ISSUE THREAD

**Issue by rorysedgwick** [influxdata/helm-charts#119]
**Telegraf Helm chart version: 1.7.7**
**Telegraf Docker image 1.13-alpine**
**Amazon Linux on EKS**

We want to convert a field (`system_location_sectionFloorNumber`) into a tag. The following config works when passed as direct `yaml` as part of a `telegraf.conf` file:

```
[[processors.enum]]
  order = 1
  [[processors.enum.mapping]]
    dest = "system_location_sectionFloorNumber"
    field = "system_location_section"
    [processors.enum.mapping.value_mappings]
        1st = 1
        2nd = 2
        3rd = 3
        4th = 4
        5th = 5
        Basement = -1
        Ground = 0
[[processors.converter]]
  order: 2
  [[processors.converter.fields]]
    tag: [ "system_location_sectionFloorNumber" ]
```

When included as the following, as part of the `values.yaml` that is passed to the Helm chart of the Telegraf Docker image, it returns the following error:
```
  processors:
    - enum:
        order: 1
        mapping:
          field: system_location_section
          dest: system_location_sectionFloorNumber
          value_mappings:
            2nd: 2
            1st: 1
            Ground: 0
            Basement: -1
    - converter:
        order: 2
        fields:
          tag: system_location_sectionFloorNumber
```

**`E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 39: (converter.Converter.Fields) cannot unmarshal TOML array table into converter.Conversion (need slice)`**

This is the case whether the tag key is passed as
`tag: [ system_location_sectionFloorNumber ]`
```
tag:
  - system_location_sectionFloorNumber
```
etc

**Comment by russorat** [comment]
Taking your telegraf TOML and converting it to YAML, i get the following (there were also some parse errors in your toml). Could you try this?

I used this: https://toolkit.site/format.html

```
processors:
  enum:
    - order: 1
      mapping:
        - dest: system_location_sectionFloorNumber
          field: system_location_section
          value_mappings:
            1st: 1
            2nd: 2
            3rd: 3
            4th: 4
            5th: 5
            Basement: -1
            Ground: 0
  converter:
    - order: 2
      fields:
        - tag:
            - system_location_sectionFloorNumber
```

**Comment by lawliet89** [comment]
I am facing the same issue. Taking what @russorat has suggested, the chart renders:

```toml
    [[processors.0]]
      fields = [
      ]
      order = 2
    [[processors.0]]
      mapping = [
      ]
      order = 1
```

**Comment by lawliet89** [comment]
@rawkode I noticed that there were some fixes to the TOML generation in b447ad0591fc7b8535a4439fdbbf533dffee4d8c that you committed. (Cannot find the GH user of the author).

Considering the "target" TOML that I am trying to acheive:

```toml
# CloudSQL
[[processors.enum]]
  [[processors.enum.mapping]]
    field = "state"
    dest = "state_code"
    default = -1

    # database/state https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql
    [processors.enum.mapping.value_mappings]
      RUNNING = 1
      RUNNABLE = 1
      SUSPENDED = 2
      PENDING_CREATE = 3
      MAINTENANCE = 4
      UNKNOWN_STATE = 0

# Uptime
[[processors.converter]]
  [processors.converter.fields]
    integer = ["check_passed", "content_mismatch"]

    tag = ["error_code", "http_status"]
```

The correct YAML should be 

```yaml
  processors:
    # For CloudSQL
    # database/state https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudsql
    - enum:
        - mapping:
            field: state
            dest: status_code
            default: -1
            value_mappings:
              RUNNING: 1
              RUNNABLE: 1
              SUSPENDED: 2
              PENDING_CREATE: 3
              MAINTENANCE: 4
              UNKNOWN_STATE: 0
    # Uptime
    - converter:
        fields:
          integer: ["check_passed", "content_mismatch"]
          tag: ["error_code", "http_status"]
```

`v1.7.31` of the chart now renders 

```toml
    [[processors.enum]]
    [[processors.converter]]
      [[processors.converter.fields]]
        integer = [
            "check_passed",
            "content_mismatch"
        ]
        tag = [
            "error_code",
            "http_status"
        ]
```

- `converter` is fixed, but `enum` is not fixed.

**Comment by russorat** [comment]
COuld we use a format similar to the Telegrafs CRD?: https://github.com/influxdata/influxdb/blob/master/pkger/testdata/telegraf.yml

**Comment by andreykaipov** [comment]
Just ran into this. Looking at the templating code, I don't really see a straightforward way of implementing this. The chart inputs aren't really 1-1 with Telegraf's TOML config as the chart makes some strong assumptions for user convenience.

For example, for the more common `rename` processor, our chart values would look like this:

```yaml
processors:
- rename:
    replace:
      tag: hostname
      dest: host
- rename:
    replace:
      tag: wow
      dest: hello
```

Within Telegraf that's actually represented (the YAML-equivalent of its TOML) as the following:

```yaml
processors:
  rename:
  - replace:
    - tag: hostname
      dest: host
    - tag: wow
      dest: hello
```

Because TOML is far from obvious, I think comparing it to the YAML-equivalent makes the assumption easier to see: each entry in our chart's processors list is always assumed to be a list of lists of objects and never just a list of objects. However, the `converter` doesn't follow that assumption:

```yaml
processors:
  converter:
  - tags:
      measurement: []
      string: []
```

I haven't really looked through all of the processors, but there's definitely a few whose syntax is like the converter, so they won't work with this chart either. Unfortunately, apart from explicitly checking for these special cases or refactoring the chart values to be 1-1 with Telegraf's TOML, I can't see this ever being addressed.

Best solution is probably to introduce a `rawConfig` value for the most flexibility.

**Comment by lawliet89** [comment]
My current workaround is to:

- Separately create a `ConfigMap`
- Mount it with `volumes` and set its `mountPoints`  to some path
- Set `.args` with a new `--config-directory` flag.


```yaml
volumes:
  - name: config
    configMap:
      name: my-custom-config
mountPoints:
  - name: config
    mountPath: /additional-config

args:
  - "--config=/etc/telegraf/telegraf.conf",
  - "--config-directory=/additional_config"
```
