### ISSUE TITLE
[chronograf] Support loading custom dashboards

### ISSUE THREAD

**Issue by mkerins** [influxdata/helm-charts#121]
It doesn't seem to be possible to include a custom dashboard when installing the chronograf chart. The way I would do it if I was writing the `Deployment` myself is to create a `ConfigMap` with the file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: chronograf-dashboard
data:
  custom-dashboard.json: |
    {
      "id": "custom-dashboar",
      "measurement": "apache",
      "app": "apache",
      ...
    }
```
Then mount it:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  labels:
    app: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
        - name: chronograf
          image: chronograf:latest
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: dashboard-volume
            mountPath: /usr/share/chronograf/resources
      volumes:
        - name: dashboard-volume
          configMap:
            name: chronograf-dashboard
```
I'm willing to work on this but waiting on my company to sign the CCLA. In the meantime is there another way to include a custom dashboard? Thanks.
