### ISSUE TITLE
[Telegraf] An option required to mount volumes from secrets 

### ISSUE THREAD

**Issue by rayalaka** [influxdata/helm-charts#213]
We would like to deploy the telegraf helm chart on Openshift and we are looking for an option to mount a secret in order to inject certificates into the pod. But, the telegraf helm chart supports only config map as volume mounting option. Request you to update the helm chart to support volume mounting option from secret or please suggest us a solution to inject the certificates from secret.

We are actually looking for an option like the way you provided in influxdb helm chart.
 
```
From influxdb chart
  | # volumes:
  | #   - name:   ssl-cert-volume
  | #     secret:
  | #         secretName: secret-name
  | # mountPoints:
  | #   - name:   ssl-cert-volume
  | #       mountPath: /etc/ssl/certs/selfsigned/
  | #       readOnly: true

```

**Comment by rayalaka** [comment]
May I know the update in case if any on this issue. Please let us know the status as we are blocked due to this issue.

**Comment by rawkode** [comment]
This isn't actively being worked on, but we'd happily accept PRs

**Comment by alespour** [comment]
Since #88, supports all/any mounting option.

Input:
```yaml
volumes:
  - name: ssl-cert-volume
    secret:
      secretName: secret-name
mountPoints:
  - name: ssl-cert-volume
    mountPath: /etc/ssl/certs/selfsigned/
    readOnly: true
```

Output:
```yaml
      container:
        volumeMounts:
        - mountPath: /etc/ssl/certs/selfsigned/
          name: ssl-cert-volume
          readOnly: true
      volumes:
      - name: ssl-cert-volume
        secret:
          secretName: secret-name
```
