### ISSUE TITLE
influxdb2 job-setup-admin.yaml does not take nodeSelector into account

### ISSUE THREAD

**Issue by Mierpo** [influxdata/helm-charts#256]
**The problem**

Problem file:

https://github.com/influxdata/helm-charts/blob/2ee220c6557c8538dc465ebb8560fde200c47d8a/charts/influxdb2/templates/job-setup-admin.yaml

Values.yaml in influxdb 2: https://github.com/influxdata/helm-charts/blob/2ee220c6557c8538dc465ebb8560fde200c47d8a/charts/influxdb2/values.yaml contains a nodeSelector field. This field is correctly take into account for deployments, such as stateful sets. However, for the job-setup-admin.yaml, the nodeSelector is not taken into account.

**The fix**

I assume the syntax for "Job" kind resources in k8s follows the same structure as "Pod" kind resources, which means the fix should be simple. Just add this to the job-setup-admin.yaml:

```
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
      {{- end }}
```

Without this, hybrid clusters running linux and windows nodes will run into issues where the job-setup-admin.yaml is executed on a Windows node and fails.

**Possible symptoms**

Note: The following behavior was noticed when running the influxdb2 helm chart on a hybrid AWS EKS cluster (k8s version 1.18), with the following changes to Values.yaml:

```
    values:
      image:
        pullPolicy: Always
      persistence:
        storageClass: "gp2"
        size: 4Gi
      adminUser:
        create: true
        organization: "influxdata"
        bucket: "default"
        user: "admin"
        password: "{{ influxdb_admin_token_base64 | b64decode }}"
      nodeSelector:
        kubernetes.io/os: "linux"
```

The symptoms of the failed admin token job can be seen in the influxdb2 pod as:

```
Warning  Unhealthy               14m   kubelet                  Readiness probe failed: Get http://[REDACTED]:8086/health: dial tcp [REDACTED]:8086: connect: connection refused
```

It can also be seen in the Job resource as:

```
  Normal   SuccessfulCreate  15m   job-controller  Created pod: influxdb2-create-admin-user-wjgds
  Normal   SuccessfulDelete  13m   job-controller  Deleted pod: influxdb2-create-admin-user-wjgds
  Warning  DeadlineExceeded  13m   job-controller  Job was active longer than specified deadline
```

In AWS EKS specifically, the problem manifests itself like this:

```
namespace 41m         Warning   FailedCreatePodSandBox   pod/influxdb2-create-admin-user-p2pv6     Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "[REDACTED]" network for pod "influxdb2-create-admin-user-p2pv6": networkPlugin cni failed to set up pod "influxdb2-create-admin-user-p2pv6_namespace" network: failed to parse Kubernetes args: pod does not have label vpc.amazonaws.com/PrivateIPv4Address
```

I was able to check where the pods of this job were being scheduled, and it turns out to be the windows node. I did this by describing the Job, then describing the Pod before the Job had a chance to delete it after roughly 2 minutes.
