### ISSUE TITLE
InfluxDB chart 4.9.13 has wrong ingressClassName defaults

### ISSUE THREAD

**Issue by jonkerj** [influxdata/helm-charts#277]
In 108378f / #272 , logic was implemented to template an optional ingressClassName. When I do not specify this class using values, it gives me an ingress resources with class `nil`, instead of not templating the class. I've tested this with a couple of Helm versions:

- CLI v3.2.1
- CLI v3.5.2
- The client built in helm-operator v1.2.0 (v3.1.2 according to its `go.mod`)

For example:
```
$ helm template --set ingress.enabled=true -s templates/ingress.yaml influxdata/influxdb
---
# Source: influxdb/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-influxdb
  labels:
    helm.sh/chart: influxdb-4.9.13
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.8.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  ingressClassName: nil
  rules:
  - host: influxdb.foobar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: RELEASE-NAME-influxdb
          servicePort: 8086
```

When I change the class to `null` instead of `nil`, it does work:
```
helm template --set ingress.enabled=true --set ingress.className=null -s templates/ingress.yaml influxdata/influxdb
---
# Source: influxdb/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-influxdb
  labels:
    helm.sh/chart: influxdb-4.9.13
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.8.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
spec:
  rules:
  - host: influxdb.foobar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: RELEASE-NAME-influxdb
          servicePort: 8086
```

So, I believe the default should be changed to `null`. I will open an PR to fix this.
