### ISSUE TITLE
telegraf-ds chart can not be used with kustomize as post renderer

### ISSUE THREAD

**Issue by gerasym** [influxdata/helm-charts#289]
Because of the comments in https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-ds/templates/daemonset.yaml#L18 kustomize fails with `yaml: invalid trailing UTF-8 octet` 

If apply patch to drop the annotations it works, but we then have to manually restart daemonset to apply config changes.

```
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: telegraf-telegraf-ds
  spec:
    template:
      metadata: 
        labels:
          app: telegraf
          log_type: telegraf       
        annotations:
          $patch: delete
 ```

Is it possible to drop the comments or fix it any other way? 
We use kustomize to add our custom labels into pods. 
So the other option would be to make them configurable through helm values, and then we would not need to use kustomize with this chart.
