### ISSUE TITLE
[telegraf] ConfigMap Processors.Converter

### ISSUE THREAD

**Issue by anachristofaro** [influxdata/helm-charts#307]
Trying to use processors.converter with the follow sintax:

```
processors:
  converter:
    fields:
      integer:
        - "*faultCountsWithDetails*"
        
```
I'm getting:
```
[[processors.converter]]
  [[processors.converter.fields]]
    integer = [
        "*faultCountsWithDetails*"
    ] 
```

While expecting:
```
[[processors.converter]]
  [processors.converter.fields]
    integer = [
        "*faultCountsWithDetails*"
    ] 
```
