### ISSUE TITLE
[influxdb] how change the index engine to TSI ?

### ISSUE THREAD

**Issue by survivant** [influxdata/helm-charts#317]
there is a way to specify the index engine to TSI from the helm chart ?

**Comment by timhallinflux** [comment]
This should probably be the default.  But, changing it as the default now for others may cause some problems.  @alespour thoughts on how to do this properly?

**Comment by alespour** [comment]
The index type can be specified in custom values file with `index-version` config option, eg.

```yaml
## InfluxDB configuration
## ref: https://docs.influxdata.com/influxdb/v1.7/administration/config
config:
  reporting_disabled: false
  rpc: {}
  meta: {}
  data:
    index-version: tsi1
  ...
```

But please be aware that switching index type **with existing data** requires extra steps to be taken. For more info see [Upgrade guide](https://docs.influxdata.com/influxdb/v1.8/administration/upgrading/#switch-index-types).
