### ISSUE TITLE
Error: Service "telegraf" is invalid: spec.ports: Required value

### ISSUE THREAD

**Issue by anwareset** [influxdata/helm-charts#326]
Here is my `values.yaml`

```yaml
rbac:
  create: true
  clusterWide: true
  rules:
    - apiGroups:
        - "*"
      resources:
        - "*"
      verbs:
        - "*"
    - nonResourceURLs:
        - "*"
      verbs:
        - "get"
        - "list"
        - "watch"
config:
  outputs:
    - influxdb_v2:
        urls:
          - "http://influxdb.influxdb.svc.cluster.local:8086"
        bucket: "influxdb"
        token: "hpkusiZ6GT32S6Yl7Q_lkY7v0-6YiNlX9sTsloW5HZmAdtTuKJneVoLNODwm46cfPvTbpxPpA3Y9K38NI3Uj5Q=="
        organization: "influxdb"
  inputs:
    - kube_inventory:
        url: "https://kubernetes.default"
        bearer_token: "/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify: true
```

And I just try to install with this command

```shell
helm upgrade --install telegraf -f values.yaml influxdata/telegraf
```

Then the output will be like this
```text
Release "telegraf" does not exist. Installing it now.
Error: Service "telegraf" is invalid: spec.ports: Required value
```

I try to get logs from the `telegraf` pod
```shell
kubectl logs -f telegraf-58845d7788-b7c94
```

The output is like this
```log
2021-06-09T06:11:54Z I! Starting Telegraf 1.17.3         
2021-06-09T06:11:54Z I! Using config file: /etc/telegraf/telegraf.conf
2021-06-09T06:11:54Z I! Loaded inputs: internal kube_inventory
2021-06-09T06:11:54Z I! Loaded aggregators: 
2021-06-09T06:11:54Z I! Loaded processors: enum
2021-06-09T06:11:54Z I! Loaded outputs: influxdb_v2
2021-06-09T06:11:54Z I! Tags enabled: host=telegraf-polling-service
2021-06-09T06:11:54Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf-polling-service", Flush Interval:10s
```

The `helm upgrade --install` command shows Error message, **but the UI seems works fine**.
![2021-06-09-131817_1600x900_scrot](https://user-images.githubusercontent.com/25749089/121303503-5f03f580-c925-11eb-9393-a19b17f6e7ce.png)

**Comment by anwareset** [comment]
The workaround is set the service to disabled inside `values.yaml` since I don't need service for telegraf.
```yaml
service:
  enabled: false
```

Or It should looks like this when we need to enable it. 

```yaml
service:
  enabled: true
  type: ClusterIP
metrics:
  health:
    enabled: true
```
Then the output of `helm upgrade --install telegraf -f values.yaml influxdata/telegraf` commands will be like this
```log
NAME: telegraf
LAST DEPLOYED: Fri Jun 11 23:08:08 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To open a shell session in the container running Telegraf run the following:

  kubectl exec -i -t $(kubectl get pods -l app.kubernetes.io/name=telegraf -o jsonpath='{.items[0].metadata.name}') /bin/sh

To view the logs for a Telegraf pod, run the following:

  kubectl logs -f $(kubectl get pods -l app.kubernetes.io/name=telegraf -o jsonpath='{ .items[0].metadata.name }')
```
