### ISSUE TITLE
Deploying using postStart hook makes pod in CrashLoopBackOff because of FailedPostStartHook

### ISSUE THREAD

**Issue by mssach** [influxdata/helm-charts#336]
On deploying influxdb2 using helm with postStart hook as below.

```
lifecycle:
  postStart:
    exec:
      command: [ "sh", "-c",  "sleep 5; influx v1 dbrp create --db default --rp default-rp --bucket-id $(influx bucket list -n default --json | grep -o '\"id\": \"[^\"]*' | grep -o '[^\"]*$') --default" ]
```
     
But, I always see **FailedPostStartHook** in pod describe. so it kills the pod. Status of pod is **CrashLoopBackOff**

kubectl describe pod: `Warning - FailedPostStartHook - 1s - kubelet - Exec lifecycle hook ([sh -c sleep 5; influx v1 dbrp create --db default --rp default-rp --bucket-id $(influx bucket list -n default --json | grep -o '"id": "[^"]*' | grep -o '[^"]*$') --default]) for Container "influxdb2" in Pod "monitor1-influxdb2-0_perf(010ef5d3-a252-4cd4-a070-91f10eb4c02f)" failed - error: command 'sh -c sleep 5; influx v1 dbrp create --db default --rp default-rp --bucket-id $(influx bucket list -n default --json | grep -o '"id": "[^"]*' | grep -o '[^"]*$') --default' exited with 1: , message: "Error: invalid argument \"--default\" for \"--bucket-id\" flag: id must have a length of 16 bytes\nSee 'influx v1 dbrp create -h' for help\n"`
