### ISSUE TITLE
Telegraf helm chart aggregator tagpass and tagdrop should not generate double brackets

### ISSUE THREAD

**Issue by nicholasgibson2** [influxdata/helm-charts#375]
In the Telegraf helm chart, when specifying an aggregator tagpass or tagdrop in values.yaml the generated telegraf.conf incorrectly has double square brackets `[[aggregators.basicstats.tagpass]]` instead of single square brackets `[aggregators.basicstats.tagpass]` This issue originates from the [template helper.](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/templates/_helpers.tpl#L444) These same configs [specified in processors](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/templates/_helpers.tpl#L322) correctly generate single square brackets.

values.yaml:
```
  aggregators:
    - basicstats:
        period: "30s"
        drop_original: true
        stats:
          - "sum"
        taginclude:
          - "counter"
          - "sql_instance"
        tagpass: 
          counter:
            - "Blocked tasks"
            - "CPU usage %"
            - "Used memory (KB)"
```
expected output:
```
    [[aggregators.basicstats]]
      drop_original = true
      period = "30s"
      stats = [
        "sum"
      ]
      taginclude = [
        "counter",
        "sql_instance"
      ]
      [aggregators.basicstats.tagpass]
        counter = [
                  "Blocked tasks",
                  "CPU usage %",
                  "Used memory (KB)"
        ]
```
actual output:
```
    [[aggregators.basicstats]]
      drop_original = true
      period = "30s"
      stats = [
        "sum"
      ]
      taginclude = [
        "counter",
        "sql_instance"
      ]
      [[aggregators.basicstats.tagpass]]
        counter = [
                  "Blocked tasks",
                  "CPU usage %",
                  "Used memory (KB)"
        ]
```
