### ISSUE TITLE
[telegraf] config inputs with float values are converted to int

### ISSUE THREAD

**Issue by Nowam** [influxdata/helm-charts#382]
Steps to reproduce:
- Install chart the following `values.yaml`:
```yaml
config:
  inputs:
    - statsd:
        service_address: ":8125"
        percentiles:
          - 50.0
          - 95.0
          - 99.0
          - 99.5
        metric_separator: "_"
        allowed_pending_messages: 10000
        percentile_limit: 1000
```

Expected behavior:
deployed chart config map has percentiles as float:
```yaml
  percentiles:
    - 50.0
    - 95.0
    - 99.0
    - 99.5
```

Actual behavior:
percentiles are converted to integers:
```yaml
  percentiles:
    - 50
    - 95
    - 99
    - 99
```

This is very limiting when trying to bin metrics into buckets with a larger resolution.
Thanks!
