### ISSUE TITLE
[influxdb2] Base64 credentials from existing secret not working

### ISSUE THREAD

**Issue by cpoulsen** [influxdata/helm-charts#427]
Hi

Using base64 encoded values for existing secret isn't working. When using plain text and `stringData` everything is working

```
  values:
    adminUser:
      user: "admin"
      existingSecret: influx-auth
```

```
apiVersion: v1
kind: Secret
metadata:
  name: influx-auth
  namespace: influx
type: Opaque
data:
  admin-token: YWRtaW4=
  admin-password: YWRtaW4=
```
