### ISSUE TITLE
[Telegraf] Error on Telegraf Helm Chart update: Error parsing data

### ISSUE THREAD

**Issue by kdrozdemir** [influxdata/helm-charts#429]
Im trying to deploy telegraf helm chart on kubernetes.

> helm upgrade --install telegraf-instance -f values.yaml influxdata/telegraf

When I add modbus input plugin with holding_register i get error

> [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: Error parsing data: line 49: key `name’ is in conflict with line 2fd

my values.yaml like below

```
## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/

replicaCount: 1

image:
  repo: "telegraf"
  tag: "1.21.4"
  pullPolicy: IfNotPresent

podAnnotations: {}

podLabels: {}

imagePullSecrets: []

args: []

env:
  - name: HOSTNAME
    value: "telegraf-polling-service"

resources: {}

nodeSelector: {}

affinity: {}

tolerations: []

service:
  enabled: true
  type: ClusterIP
  annotations: {}

rbac:
  create: true
  clusterWide: false
  rules: []

serviceAccount:
  create: false
  name:
  annotations: {}

config:
  agent:
    interval: 60s
    round_interval: true
    metric_batch_size: 1000000
    metric_buffer_limit: 100000000
    collection_jitter: 0s
    flush_interval: 60s
    flush_jitter: 0s
    precision: ''
    hostname: '9825128'
    omit_hostname: false
  processors:
    - enum:
        mapping:
          field: "status"
          dest: "status_code"
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3
  inputs:
    - modbus:
        name: "PS MAIN ENGINE"
        controller: 'tcp://192.168.0.101:502'
        slave_id: 1
        holding_registers: 
          - name: "Coolant Level"
            byte_order: CDAB
            data_type: FLOAT32
            scale: 0.001
            address: [51410, 51411]
    - modbus:
        name: "SB MAIN ENGINE"
        controller: 'tcp://192.168.0.102:502'
        slave_id: 1
        holding_registers: 
          - name: "Coolant Level"
            byte_order: CDAB
            data_type: FLOAT32
            scale: 0.001
            address: [51410, 51411]
  outputs:
    - influxdb_v2:
        token: token
        organization: organisation
        bucket: bucket
        urls:
          - "url"

metrics:
  health:
    enabled: true
    service_address: "http://:8888"
    threshold: 5000.0
  internal:
    enabled: true
    collect_memstats: false

pdb:
  create: true
  minAvailable: 1
```

**Comment by alespour** [comment]
I think for cases like this, possibility to specify raw config is the best solution #358.

**Comment by kdrozdemir** [comment]
hi @alespour, thank you for your reply.
I have tried solution at the end of #119 but i dont know if i did it right.

- deleted config section of my values.yaml
- added 
```
args:
  - "--config=/etc/telegraf/telegraf.config"`
  - "--config-directory=/additional_config"
mountPoints:
  - name: config
  - mountPath: /additional_config
```
to my values.yaml (if i add volumes with name config to yaml, i get an error: Duplicate value: "config")
- added my telegraf.config file to /additional_config directory

its not working. telegraf running with default values.
