### ISSUE TITLE
[Telegraf] ConfigMap telegraf Yaml => Toml error

### ISSUE THREAD

**Issue by lpaulusLohr** [influxdata/helm-charts#433]
Hi,

I have an problem with ConfigMap Yaml to Toml parsing : 

I want this  : 
```
    [[inputs.mqtt_consumer.json_v2.object]]
        path = "@this"
        tags = ["device","data.type","owner"] 
```

But the helm parsing template render it like : 
```
    [[inputs.mqtt_consumer.json_v2.object]]
        path = "@this"
        tags = "[device data.type owner]"
```

My Yaml :

```
          object:
            path: "@this"
            tags:
              - "device"
              - "data.type"
              - "owner"
```

I found the problem is here in the template  *_helpers.tpl*  l.277
```
          [inputs.{{ $input }}.{{ $key }}.{{ $k }}]
                {{- range $foo, $bar := $v }}
            {{ $foo }} = {{ $bar | quote }}
```

**Comment by alespour** [comment]
Could you please try the latest chart with `--set tplVersion=2`.

[README.md#telegraf-configuration](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/README.md#telegraf-configuration)

**Comment by alespour** [comment]
Should be
```toml
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name_path = "device"
    [[inputs.mqtt_consumer.json_v2.object]]  
      path = "@this"
      tags = [
        "device",
        "data.type",
        "owner"
      ]   
```
for
```yaml
        json_v2:
          - measurement_name_path: "device"
            object:
              - path: "@this"
                tags:
                  - "device"
                  - "data.type"
                  - "owner"
```

**Comment by lpaulusLohr** [comment]
It's a Match 👍 : 

```
json_v2:
  measurement_name_path: "device"
  object:
    path: "@this"
    tags:
      - "device"
      - "data.type"
      - "owner"
 ```

**Comment by alespour** [comment]
I see :)
OK to close the issue?

**Comment by lpaulusLohr** [comment]
I did not pay attention, but there is a problem on the title of the "section", there is only 1 hook instead of 2

```javascript
[[inputs.mqtt_consumer]]    
  data_format = "json_v2"

  topics = [
    "XXXX"
  ]
  [inputs.mqtt_consumer.json_v2]  
    measurement_name_path = "device"
    [inputs.mqtt_consumer.json_v2.object]  
      path = "@this"
      tags = [
        "device",
        "data.type",
        "owner"
      ]
```

**Comment by lpaulusLohr** [comment]
This is my config, check if I'm wrong but I use lists :
```
    - mqtt_consumer:
        topics:
          - "XXXX"
        data_format: "json_v2"
        json_v2:
          measurement_name_path: "device"
          object:
            path: "@this"
            tags:
              - "device"
              - "data.type"
              - "owner"
 ```
