### ISSUE TITLE
influxdb backup retention fails due to missing S3_ENDPOINT

### ISSUE THREAD

**Issue by oxr463** [influxdata/helm-charts#464]
The [values.yaml](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/values.yaml#L286) file lists the s3.endpointUrl as optional:

>   \#   ## Optional. Specify if you're using an alternate S3 endpoint.

However, the backup retention pod is giving me the following error when it isn't set:

```
Loaded plugins: ovl, priorities 
Resolving Dependencies 
--> Running transaction check 
---> Package jq.x86_64 0:1.5-1.amzn2.0.2 will be installed 
--> Processing Dependency: libonig.so.2()(64bit) for package: jq-1.5-1.amzn2.0.2.x86_64 
--> Running transaction check 
---> Package oniguruma.x86_64 0:5.9.6-1.amzn2.0.4 will be installed 
--> Finished Dependency Resolution 
 
Dependencies Resolved 
 
================================================================================ 
 Package         Arch         Version                    Repository        Size 
================================================================================ 
Installing: 
 jq              x86_64       1.5-1.amzn2.0.2            amzn2-core       154 k 
Installing for dependencies: 
 oniguruma       x86_64       5.9.6-1.amzn2.0.4          amzn2-core       127 k 
 
Transaction Summary 
================================================================================ 
Install  1 Package (+1 Dependent package) 
 
Total download size: 281 k 
Installed size: 890 k 
Downloading packages: 
-------------------------------------------------------------------------------- 
Total                                              3.4 MB/s | 281 kB  00:00 
Running transaction check 
Running transaction test 
Transaction test succeeded 
Running transaction 
  Installing : oniguruma-5.9.6-1.amzn2.0.4.x86_64                           1/2 
  Installing : jq-1.5-1.amzn2.0.2.x86_64                                    2/2 
  Verifying  : jq-1.5-1.amzn2.0.2.x86_64                                    1/2 
  Verifying  : oniguruma-5.9.6-1.amzn2.0.4.x86_64                           2/2 
 
Installed: 
  jq.x86_64 0:1.5-1.amzn2.0.2 
 
Dependency Installed: 
  oniguruma.x86_64 0:5.9.6-1.amzn2.0.4 
 
Complete! 
 
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] 
To see help text, you can run: 
 
  aws help 
  aws <command> help 
  aws <command> <subcommand> help 
 
aws: error: argument --endpoint-url: expected one argument 
```

Here is the spec from the Job that gets created by the CronJob:

```
spec:
      containers:
      - args:
        - /scripts/backup-retention.sh
        command:
        - /bin/bash
        env:
        - name: AWS_CONFIG_FILE
          value: /var/secrets/aws/credentials
        - name: DAYS_TO_RETAIN
          value: "30"
        - name: S3_BUCKET
          value: influxdb-backup
        - name: S3_ENDPOINT
        image: amazon/aws-cli
        imagePullPolicy: Always
        name: aws-cli
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /var/secrets/aws/
          name: aws-credentials-secret
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: influxdb
      serviceAccountName: influxdb
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: influxdb-backup-retention
        name: scripts
      - name: aws-credentials-secret
        secret:
          defaultMode: 420
          secretName: influxdb-backup
```

Source: https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/files/backup-retention-script.sh#L5
