### ISSUE TITLE
Kapacitor issue problem with values (envVars)

### ISSUE THREAD

**Issue by robbyq92** [influxdata/helm-charts#487]
Hi all, i have problem with kapacitor, i try to insert envVars: but i have problem if i run helm:

envVarS:
`envVars:
  KAPACITOR_INFLUXDB_0_URLS_0="http://xxx:8086"
  KAPACITOR_INFLUXDB_0_USERNAME="user"
  KAPACITOR_INFLUXDB_0_PASSWORD="pass"
  KAPACITOR_INFLUXDB_0_INSECURE_SKIP_VERIFY=true
  KAPACITOR_INFLUXDB_0_SUBSCRIPTION_PROTOCOL="http"
    # KAPACITOR_HOSTNAME=kapacitor
    # KAPACITOR_INFLUXDB_0_URLS_0=http://url:8086

influxURL: "http://xxxx:8086"
`
i need put url and deploy helm, the influxUrl is mandatory... so i need to put, but if i run helm i have this error:

`Error: INSTALLATION FAILED: template: kapacitor/templates/deployment.yaml:37:39: executing "kapacitor/templates/deployment.yaml" at <.Values.envVars>: range can't iterate over KAPACITOR_INFLUXDB_0_URLS_0="http:/xxx:8086"
 KAPACITOR_INFLUXDB_0_USERNAME="user" KAPACITOR_INFLUXDB_0_PASSWORD="pass" KAPACITOR_INFLUXDB_0_INSECURE_SKIP_VERIFY=true`

so if u i comment envVars it run, but i have 401 error i need to insert password influxdbv2 and user, so i think this need in envVars insert.

**Comment by robbyq92** [comment]
i have this error in pod, of corse, for this i need to inyect password and user, but i cant.

lvl=error msg="encountered error" service=run err="open server: open service *influxdb.Service: failed to link subscription on startup: invalid response: code 401"
run: open server: open service *influxdb.Service: failed to link subscription on startup: invalid response: code 401

**Comment by alespour** [comment]
That's invalid YAML input. Correct one is

```yaml
envVars:
  KAPACITOR_INFLUXDB_0_URLS_0: "http://xxx:8086"
  KAPACITOR_INFLUXDB_0_USERNAME: "user"
  KAPACITOR_INFLUXDB_0_PASSWORD: "pass"
  KAPACITOR_INFLUXDB_0_INSECURE_SKIP_VERIFY: true
  KAPACITOR_INFLUXDB_0_SUBSCRIPTION_PROTOCOL: "http"
# KAPACITOR_HOSTNAME=kapacitor
# KAPACITOR_INFLUXDB_0_URLS_0=http://url:8086

influxURL: "http://xxxx:8086"
```
