### ISSUE TITLE
Missing service.labels to the service in Influxdb2

### ISSUE THREAD

**Issue by MaxThom** [influxdata/helm-charts#518]
Chart: InfluxDB2
Issues: Service extra labels are not added to the service

hey,

i'm trying to add extra label to the service. In the helm chart values, I see
```yaml
service:
  type: ClusterIP
  port: 80
  targetPort: 8086
  annotations: {}
  labels: {}
  portName: http
```
but when I add extra labels there, they are not transfered on the actual service.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels: {{- include "influxdb.labels" . | nindent 4 }}
```

I tried to the a PR, but I cant manage push to my branch... Unauthorize all the time.
This is what its needed I believe:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels: {{- include "influxdb.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
```

Thanks
