### ISSUE TITLE
Quantile Aggregator Plugin configuration not parsed correctly

### ISSUE THREAD

**Issue by joan-mido-qa** [influxdata/helm-charts#524]
Plugin Configuration:

```yaml        
- quantile:
  name_suffix: _quantile
  namepass:
   - consumer_events
   - azure_events
  period: 60s
  drop_original: true
  quantiles:
   - 0.99
 ```

_helpers.tpl converts float64 numbers to int64, changing all quantiles values to 0.

```yaml        
- quantile:
  name_suffix: _quantile
  namepass:
   - consumer_events
   - azure_events
  period: 60s
  drop_original: true
  quantiles:
   - 0
 ```

Telegraf fails to start because it expects a floating number.

**Comment by evanfpearson** [comment]
A similar problem occurs with the histogram aggregator:
```yaml
- histogram:
  period: "30s"
  drop_original: true
  config:
  - buckets: [0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]
    measurement_name: "k6-gauge"
    fields: ["vus", "vus_max", "write_time"]
```
as above, these floating points are converted to ints, when telegraf expects floats.
