### ISSUE TITLE
Incorrect inputs tpl for YAML <=> TMOL

### ISSUE THREAD

**Issue by zhenzh** [influxdata/helm-charts#532]
When I try to add an mqtt consumer input into the telegraf through helm installation, the helm chart can not correctly convert my yaml formated input configuration to tmol.
```
config:
  inputs:
  - mqtt_consumer:
      topic_parsing:
        measurement: test
```
The yaml below was converted to:
```
[[inputs.mqtt_consumer]]
  [inputs.mqtt_consumer.topic_parsing]      <------ which should be [[inputs.mqtt_consumer.topic_parsing]]
    measurement = "test"
```

**Comment by zhenzh** [comment]
I have check your tpl definitions which is really complex and hard to fully consider all kinds of yaml to tmol cases. Why not directly using text format for config section to avoid thinking of complex converting between yaml and tmol?

**Comment by MyChaOS87** [comment]
Stumbled upon this as I had another issue when parsing my config.

You should be able to solve your issue by using a `-` in front of measurement, I guess:
```
config:
  inputs:
  - mqtt_consumer:
      topic_parsing:
        - measurement: test
```

but you also should use the tplVersion=2 parameter (which helped me out, as topics were falsely placed after the `[[inputs.mqtt_consumer.topic_parsing]]` otherwise
