### ISSUE TITLE
Yaml order incorrect when creating the config

### ISSUE THREAD

**Issue by micw** [influxdata/helm-charts#541]
Hello,

I have the following configuration:

```yaml
        inputs:
          - mqtt_consumer:
              servers: ["tcp://192.168.1.3:1883"]
              username: consumer
              password: something
              topics:
                - solar/+/0/power
              data_format: value
              data_type: float
              topic_parsing:
                - topic: solar/116182009632/0/+
                  measurement: _/_/measurement
                  tags: inverter/channel/_
```

But when the chart creates toml from it, the result is:

```toml
    [[inputs.mqtt_consumer]]
      data_format = "value"
      data_type = "float"
      password = "something"
      servers = [
        "tcp://192.168.1.3:1883"
      ]
      [[inputs.mqtt_consumer.topic_parsing]]
         measurement = "_/_/measurement"
         tags = "inverter/channel/_"
         topic = "solar/+"
      topics = [
        "solar/+/0/power"
      ]
      username = "consumer"
```

topics and username come after topic_parsing and cannot be handled correctly.

I get the error "plugin inputs.mqtt_consumer: line 26: configuration specified the fields ["topics" "username"], but they weren't used
"

**Comment by micw** [comment]
I found an (ugly) workaround. By specifying the topic parsing as it would be an input, I can create the desired result:

```
          - mqtt_consumer:
            [...]
          - mqtt_consumer.topic_parsing:
                  topic: solar/#
                  measurement: _/_/_/measurement
                  tags: _/inverter/channel/_
```
