### ISSUE TITLE
[DOC] how to build nested telegraf.conf

### ISSUE THREAD

**Issue by jcpunk** [influxdata/helm-charts#579]
The instructions are a bit vague and I'm unable to sort how to build a telegraf.conf like:

```toml
    [[inputs.kafka_consumer]]
      brokers = [
        "kafka-bootstrap.kafka:9092"
      ]
      client_id = "opmon-telegraf"
      consumer_group = "opmon-telegraf"
      data_format = "json_v2"
      topics = [
        "opmon"
      ]
      version = "3.4.0"
      [[inputs.kafka_consumer.json_v2]]
        measurement_name_path = "measurement"
        timestamp_format = "2023-07-13T14:59:51Z"
        timestamp_path = "time"
          [[inputs.kafka_consumer.json_v2.object]]
            tags = [ "tags" ]
          [inputs.kafka_consumer.json_v2.object.fields]
            key = "fields"
```
