### ISSUE TITLE
Cannot change interval of inputs.internal outside of default

### ISSUE THREAD

**Issue by thopewell** [influxdata/helm-charts#591]
My telegraf configuration has:

```
  config:
    agent:
      interval: "2s"
```

I wanted to lower the frequency of the internal metrics sent to Influx (described (here)[https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internal]) because the cost on Influx cloud is not completely insignificant at the 50 or so instances we have running (each telegraf sends about 2Gb of health metrics data per month).

This line of code: https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/templates/configmap.yaml#L27
overwrites any custom configuration of the input plugin.

This works around the issue but seems odd:

```
  metrics:
    health:
      enabled: true
    internal:
      enabled: false

    inputs:
      - internal:
          interval: "60s"
          collect_memstats: false
```

Interestingly, I tried changing the default to 60s, but started getting Rabbitmq errors on startup:

```
2023-08-15T23:54:57Z E! [telegraf] Error running agent: starting input inputs.amqp_consumer: error declaring queue: Exception (404) Reason: "NOT_FOUND - home node 'rabbit@xxxx of durable queue 'influx_metric_telegraf' in vhost '/' is down or inaccessible"
```
