### ISSUE TITLE
influxdb: helm chart doesn't create admin user

### ISSUE THREAD

**Issue by jas02** [influxdata/helm-charts#607]
Hi,

I am trying to automate installation of InfluxDB using Ansible and InfluxDB Helm chart .Installation works, but for some reason Helm doesn't create initial admin user during the installation and I have to manually create initial account after the installation through web interface.

Helm chart version: 4.12.5
App version: 1.8.10

Corresponding values in Helm chart:

```
setDefaultUser:
  enabled: true
  user:
    existingSecret: influxdb-auth

config:
  http:
    auth-enabled: true
```

Influxdb-auth secret:

```
kind: Secret
data:
  influxdb-password: AAAA=
  influxdb-user: BBB=
```

What am I missing? Is this bug, or I have to setup something else?

BR

L.
