### ISSUE TITLE
Duplicated HostIP in telegraf-ds

### ISSUE THREAD

**Issue by caiocfer** [influxdata/helm-charts#608]
When deploying telegraf-ds, in the daemonset the HostIP is duplicated, they are both written in the values.yaml and daemonset.yaml

```
  - name: HOSTIP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```
from: https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-ds/values.yaml#L39

```
        env:
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
{{ toYaml .Values.env | indent 8 }}
```
from: https://github.com/influxdata/helm-charts/blob/master/charts/telegraf-ds/templates/daemonset.yaml#L43

When deployed the telegraf-ds' daemonset it's found:

```
        env:
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

I submitted a PR to fix this: https://github.com/influxdata/helm-charts/pull/603
