### ISSUE TITLE
telegraf-ds: support exposing secret key as env

### ISSUE THREAD

**Issue by rawkode** [influxdata/helm-charts#63]
This will make configuring InfluxDB 2 much easier

```
secretToEnv:
 - name: my-secret
   key: my-key
   env: TOKEN
```
