### ISSUE TITLE
[telegraf-ds] inputs.net provides no data

### ISSUE THREAD

**Issue by yellowpattern** [influxdata/helm-charts#636]
After getting telegraf to start providing data as a daemon set, I then tried to get some network information (it isn't included in the default set of metrics) by adding this to the configMap:

    [[inputs.net]]
      ignore_protocol_stats = true
      interfaces = [ "ens*"]

But there's nothing. No output anywhere.

**Comment by yellowpattern** [comment]
Sorry, I lie, I get statistics for "eth0" but not the physical interfaces.

**Comment by yellowpattern** [comment]
The config sets HOST_PROC to be /hostfs/proc BUT /hostfs/proc/net/dev is the same as /proc/net/dev. Problem: /proc can't be ounted under /proc.

**Comment by yellowpattern** [comment]
I found a way...
```
spec:
...
  template:
...
    spec:
...
      volumeMounts:
        - name: procnet
          mountPath: /hostfs/proc/net
...
      volumes:
        - name: procnet
          hostPath:
            path: /proc/net
            type: ''
```
