### ISSUE TITLE
Multiple input plugins exposed via Type LoadBalancer not working

### ISSUE THREAD

**Issue by camrossi** [influxdata/helm-charts#639]
I have a config with 2 `http_listener_v2` plugins listening on 2 different ports. 
When I try to deploy this config with Helm it fails as the generated Services are having duplicate names: 

```
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    helm.sh/chart: telegraf-1.8.45
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    name: "http-listener-v2" <====
  - port: 8081
    targetPort: 8081
    name: "http-listener-v2" <====
  - port: 9273
    targetPort: 9273
    name: "prometheus-client"
  selector:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf
```

This seems expected from what I can see in the [Template](https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/templates/service.yaml#L37): All the Services have the `name` hardcoded. 

We should probably have some logic to detect if the same input plugin is used and then add the port in the name or use the `alias`

below my value config for the relevant part:

```
inputs:
    - http_listener_v2:
        alias: "fab1"
        service_address: ":8080"
        paths: ["/"]
        tags:
          fabric: "fab1"
        data_format: "json_v2"
        json_v2: &json_v2_config
       <SNIP>
    - http_listener_v2:
        alias: "fab2"
        service_address: ":8081"
        paths: ["/"]
        tags:
          fabric: "fab2"
        data_format: "json_v2"
        json_v2: *json_v2_config
```

For now I patched the service Template to include the port in the name, not sure if there is a supported way to do this that I am missing ?

```
    {{- if eq $key "http_listener_v2" }}
  - port: {{ trimPrefix ":" $value.service_address | int64 }}
    targetPort: {{ trimPrefix ":" $value.service_address | int64 }}
    name: {{ printf "http-listener-v2-%d" (trimPrefix ":" $value.service_address | int64 ) }} <===
    {{- end }}
```
