### ISSUE TITLE
helm_charts influxdb, backup_cronjob template has misconfiguration.

### ISSUE THREAD

**Issue by plalwa** [influxdata/helm-charts#670]
```
      - name: AZURE_STORAGE_CONNECTION_STRING
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.backup.azure.storageAccountSecret }}
                    key: connection-string
```

the template causes it to fail with below error  `spec.jobTemplate.spec.template.spec.containers[0].env[3].valueFrom.secretKeyRef.name: Invalid value: `
