### ISSUE TITLE
Telegraf helm chart output tagpass and tagdrop should not generate double brackets

### ISSUE THREAD

**Issue by peterbaumert** [influxdata/helm-charts#688]
Same issue like in #375 just this time for outputs.

 values.yaml:
 
 ```
   outputs:
     - basicstats:
         period: "30s"
         drop_original: true
         stats:
           - "sum"
         taginclude:
           - "counter"
           - "sql_instance"
         tagpass: 
           counter:
             - "Blocked tasks"
             - "CPU usage %"
             - "Used memory (KB)"
 ```
 
 expected output:
 
 ```
     [[outputs.basicstats]]
       drop_original = true
       period = "30s"
       stats = [
         "sum"
       ]
       taginclude = [
         "counter",
         "sql_instance"
       ]
       [outputs.basicstats.tagpass]
         counter = [
                   "Blocked tasks",
                   "CPU usage %",
                   "Used memory (KB)"
         ]
 ```
 
 actual output:
 
 ```
     [[outputs.basicstats]]
       drop_original = true
       period = "30s"
       stats = [
         "sum"
       ]
       taginclude = [
         "counter",
         "sql_instance"
       ]
       [[outputs.basicstats.tagpass]]
         counter = [
                   "Blocked tasks",
                   "CPU usage %",
                   "Used memory (KB)"
         ]
 ```
