### ISSUE TITLE
InfluxDB Clustered 3 - appinstances.kubecfg.dev CRD inclusion of empty arrays causes ArgoCD to behave as if the CRD is out of sync

### ISSUE THREAD

**Issue by bryantidd** [influxdata/helm-charts#698]
In the appinstances.kubecfg.dev CRD there are three empty arrays, at lines 8, 11, and 15. When using ArgoCD to install InfluxDB Clustered 3, the CRD is always considered out of sync because the applied CRD will not have the empty arrays. 

This makes InfluxDB 3 seem misconfigured or out of sync with it's gitops codebase.

**Comment by SamLoub** [comment]
Hi, I had the same issue. You can fix it in ArgoCD by adding `ignoreDifferences` values.
Here is my fix :
```
ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: appinstances.kubecfg.dev
    jsonPointers:
      - /spec/names/categories
      - /spec/names/shortNames
      - /spec/versions/0/name
      - /spec/versions/0/additionalPrinterColumns
```
