### ISSUE TITLE
using telegraf-ds and influx as subcharts 

### ISSUE THREAD

**Issue by butson** [influxdata/helm-charts#71]
It would be nice to be able put together an application helm chart that installs telegraf and influx as subcharts (grafana also).  In order to do this.  simple change to telegraf to use tpl function on output config can be done to accomplish this:

values.yaml:
```
telegraf:
  enabled: false
  config:
    outputs:
    - influxdb:
        urls:
          - "http://{{ .Release.Name }}-influxdb.{{ .Release.Namespace }}.svc:8086"
```

configmap.yaml:
   would need to pass full context to output template and use tpl for string values.
` {{ template "outputs" .  }}`

and outputs would be changed as.

```{{- define "outputs" -}}
{{- $context := . -}}
{{- range $outputIdx, $configObject := .Values.config.outputs -}}
...
          {{- if eq $tp "string" }}
      {{ $key }} = {{ tpl $value $context | quote }}
...```
