### ISSUE TITLE
[telegraf] Cannot mount additional config files in /etc/telegraf/telegraf.d due to non-subPath volume mount

### ISSUE THREAD

**Issue by sotoiwa** [influxdata/helm-charts#721]
### Problem

The current `volumeMounts` configuration in the Telegraf Helm chart mounts the entire ConfigMap to `/etc/telegraf` without using `subPath`:

```yaml
volumeMounts:
  - name: config
    mountPath: /etc/telegraf
```

This approach blocks users from mounting additional configuration files (e.g., `/etc/telegraf/telegraf.d/http.conf`) via separate `volumeMounts`, because the entire `/etc/telegraf` directory is already occupied by the initial mount.

### Proposal

To enable mounting supplemental configuration files under `/etc/telegraf/telegraf.d`, please consider changing the `volumeMounts` entry to use `subPath` and mount the main configuration file directly:

```yaml
volumeMounts:
  - name: config
    mountPath: /etc/telegraf/telegraf.conf
    subPath: telegraf.conf
    readOnly: true
```

### Benefit

This enables users to cleanly inject additional Telegraf input/output configurations via separate ConfigMaps or volumes, without conflicting with the main config mount.
