### ISSUE TITLE
Adding input.internal

### ISSUE THREAD

**Issue by max5599** [influxdata/helm-charts#79]
I'm trying to add the [input internal](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internal) to the telegraf config with the following configuration:
```
## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/
...

  inputs:
    - kubernetes:
        url: "https://$HOSTIP:10250"
        bearer_token: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify: true
    - docker: 
        endpoint: "unix:///var/run/docker.sock"
        timeout: "5s"
        perdevice: true
        total: false
        docker_label_exclude:
        - "annotation.kubernetes.io/*"
    - internal:
```
But it's not added in telegraf.conf, how can I add it?

**Comment by rawkode** [comment]
@max5599 I believe the following will work:

```yaml
- internal: {}
```

**Comment by max5599** [comment]
Thx @rawkode for your answer.
I've tried it but it's not working, but I noticed that none of the inputs are actually working, I've changed a value in output and the value of kubernetes.url and only the one in output changed.

Do you have any example of a valid yaml with inputs configuration? The default one doesn't have any.

**Comment by rawkode** [comment]
This works for me with the `telegraf` chart. Which chart are you using?

```yaml
config:
  inputs:
    - internal: {}
```
