### ISSUE TITLE
Telegraf helm Chart:- volumeMounts issue [with helm3 strict validation]

### ISSUE THREAD

**Issue by rajasree-1993** [influxdata/helm-charts#82]
hi
ERROR:- 
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[1]): unknown field "mountPath" in io.k8s.api.core.v1.Volume

Getting the above error while trying to deploy with helm3. 
I have added the volumeMounts section in telegraf values.yaml. 

  volumeMounts:
  - name: tls-config
    mountPath: /app/certs/
    configMap:
      name: "telegraf-agent-configmap"

Where this is been called in 2 places (under volumes and volumeMounts) in  deployment.yaml as shown below. 

        volumeMounts:
        {{- range .Values.volumeMounts}}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
        {{- end }}

      volumes:
      {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 6 }}
      {{- end}}

But helm3 does a strict validation where in it cannot accept mountPath in volumes and in volumeMounts mountPath turns out to be a mandatory field. 

Kindly confirm when this issue will be fixed.

**Comment by nsteinmetz** [comment]
Hi @rajasree-1993 

How can I reproduce your issue, I don't have it. Which chart `telegraf` or `telegraf-ds` and which version of it do you use ?

Thanks,

**Comment by rajasree-1993** [comment]
Issue is with telegraf chart . 
You can try deploying the chart with helm3 after providing the volumeMounts as below

volumeMounts:
  name: tls-config
  mountPath: /app/certs/
  configMap:
    name: "telegraf-agent-configmap"

**Comment by nsteinmetz** [comment]
Ok, I see the point.

With `values.yaml` having:

```yaml
volumeMounts:
  - name: tls-config
    mountPath: /app/certs/
    configMap:
      name: "telegraf-agent-configmap"
```

it leads to:

```
# Source: telegraf/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-telegraf
  labels:
    app.kubernetes.io/name: telegraf
    helm.sh/chart: telegraf-1.7.12
    app.kubernetes.io/instance: RELEASE-NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        checksum/config: 7d4014f73d96b46076f401e78260aa9dc734bfd72f7adba06d73c1ee3fece598
    spec:
      serviceAccountName: RELEASE-NAME-telegraf
      containers:
      - name: telegraf
        image: "telegraf:1.14-alpine"
        imagePullPolicy: "IfNotPresent"
        resources:
          {}
        env:
        - name: HOSTNAME
          value: telegraf-polling-service
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        - name: tls-config
          mountPath: /app/certs/
      volumes:
      - name: config
        configMap:
          name: RELEASE-NAME-telegraf
      - configMap:
          name: telegraf-agent-configmap
        mountPath: /app/certs/
        name: tls-config
```

The last block should be (beyond order or arguments) :

```yaml
      - name: tls-config
        configMap:
          name: telegraf-agent-configmap        
```

I'll let people used to helm templating fix the issue as I'm not the best in this field (nor have time for it in the coming days) - seems not managed in the other charts.

At worst but with duplication, we could have a `volumeMounts` and a `volume` lists

**Comment by rajasree-1993** [comment]
hi 

Thanks for the quick response.
Yes . Having  volumeMounts and a volume section should fix the issue.
Expecting the fix asap as this chart itself becomes incompatible with helm3 otherwise.

**Comment by rawkode** [comment]
Hi @rajasree-1993,

Thanks for your issue. I can see the problem having ran through the comments,

This is an undocumented, at-least within `values.yaml`, feature. So hopefully not too many people are using it.

However, to avoid breaking any existing deployments, I'd like to propose I fix this with the following solution:

```
volumes:
- name: tls-config
  configMap:
    name: telegraf-agent-configmap
mountPounts:
- name: tls-config
  mountPath: /etc/telegraf/conf.d/abc
```

This configuration should provide a more flexible solution going forward and we'll aim to deprecate the older option, `volumeMounts`, during our next major release.

Please let me know your thoughts.

CC @gitirabassi
