### ISSUE TITLE
initScripts is incompatible with http-enabled: true

### ISSUE THREAD

**Issue by cykl** [influxdata/helm-charts#85]
Figuring out how to both enable InfluxDB authentication and use an init script was a cumbersome process and I'm not happy with the solution I found.

Readme tells (https://github.com/influxdata/helm-charts/tree/master/charts/influxdb#starting-with-authentication):
>  To handle this setup on startup, a job can be enabled in values.yaml by setting .Values.setDefaultUser.enabled to true.

SetDefaultUser is an asynchronous process run in a dedicated container. Init scripts are run by container entrypoint. If admin user is created after init script is executed, commands are rejected because there is no admin user. If admin user is created before init script is executed, commands are rejected because init script doesn't provide, nor know, the right credentials.

It also not possible to create an admin user from the init script. 

I figured out it was possible to set INFLUXDB_ADMIN_(USER|PASSWORD) environment variables. It this case, entrypoint creates the admin user first and then provides the proper credentials to subsequent commands. 

This leads me to ask two questions:

 - Shouldn't set-auth post-install hook be superseded by another mechanism ? 
 - Is there is way to use secrets to set INFLUXDB_ADMIN_PASSWORD ?

**Comment by aqua-terra** [comment]
@cykl Do you have a workaround for this issue? I'm having the same frustrating issue where init.iql is not run and env vars are not used.

**Comment by mijaildeltoro** [comment]
Any solution/alternative for this issue

**Comment by asettouf** [comment]
I'd just like to mention that even with a `.sh` script, it's still not ran.

**Comment by brsolomon-deloitte** [comment]
> I'd just like to mention that even with a .sh script, it's still not ran, on version 4.10.4

Yup, a two-year old issue still broken on Helm chart version 4.10.6.

Setting

```yaml
  setDefaultUser:
    user:
      existingSecret: <my-secret-name>
```

does _not_ successfully run the [post-install-set-auth](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/post-install-set-auth.yaml) job.

This is as plain as day since I can `kubectl exec` into an influxdb pod:

```bash
$ curl http://localhost:8086/query -u redacted:redacted --data-urlencode "q=SHOW DATABASES"
{"error":"error authorizing query: create admin user first or disable authentication"}
$ curl -XPOST http://localhost:8086/query --data-urlencode "q=CREATE USER "redacted" WITH PASSWORD 'redacted' WITH ALL PRIVILEGES"
{"results":[{"statement_id":0}]}
$ curl http://localhost:8086/query -u redacted:redacted --data-urlencode "q=SHOW DATABASES"
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"]]}]}]}
```

**Comment by alespour** [comment]
It is not necessary to use post-install-set-auth job to set up admin user, in fact it is seems not quite suitable for this case.

With the values bellow, the following is done all at once without the job (ie. do not enable and/or configure `setDefaultUser`):
1. enable InfluxDB HTTP authentication
2. create admin user
3. run init script

```yaml
env:
- name: INFLUXDB_ADMIN_USER
  valueFrom:
    secretKeyRef:
      name: influxdb-secret
      key: influxdb-user
- name: INFLUXDB_ADMIN_PASSWORD
  valueFrom:
    secretKeyRef:
      name: influxdb-secret
      key: influxdb-password

config:
  http:
    auth-enabled: true

initScripts:
  enabled: true
  scripts:
    init.iql: |+
      CREATE DATABASE "telegraf" WITH DURATION 30d REPLICATION 1 NAME "rp_30d"
      CREATE DATABASE "iot" WITH DURATION 7d REPLICATION 1 NAME "rp_7d"
```
