### ISSUE TITLE
telegraf chart: unable to specify input tags

### ISSUE THREAD

**Issue by zmb3** [influxdata/helm-charts#97]
I'm unable to specify tags on my inputs using the `telegraf` chart.

In my values.yml I have something like this:

```
  inputs:
  - prometheus:
      kubernetes_services: 
      - http://blackbox-exporter:9115/probe?....
      metric_version: 2
      tags:
        foo: bar
```

Which gets templated into the following TOML:

```
[[inputs.prometheus]]
  alias = "blackbox"
  kubernetes_services = [
    "http://blackbox-exporter:9115/probe?...
  ]
  metric_version = 2
  [[inputs.prometheus.tags]]
    foo = "bar"
```

However, `tags` is a table, not an array, so I think it should be `[inputs.prometheus.tags]` instead of `[[inputs.prometheus.tags]]`.  Am I doing something wrong or is the template incorrect?  Any workarounds?

https://github.com/influxdata/helm-charts/blob/4eb7881ddbe9604cfb40cbad99c320e318baf0c6/charts/telegraf/templates/_helpers.tpl#L238
