### ISSUE TITLE
Telegraf: Unable to pass multiple tags options to config.processors.regex

### ISSUE THREAD

**Issue by rorysedgwick** [influxdata/helm-charts#98]
I am trying to define multiple regex rules to convert data, all operating on the `tags`.  [The telegraf docs](https://github.com/influxdata/telegraf/blob/release-1.14/plugins/processors/regex/README.md) show you can supply multiple `tags` or `fields` as subsequent blocks, and we have this running in an environment where we direct control of the `telegraf.conf`.

This config is being defined in `values.yaml` as follows: 

```
processors:
    - regex:
        namepass: mqtt_consumer
        tags:
          key: "topic"
          pattern: '''^([A-Za-z0-9\-\.]+\/){0}([A-Za-z0-9\-\.]+)[A-Za-z0-9\-\.\/]*$'''
          replacement: "${2}"
          result_key: "domain"
        tags:
          key: "topic"
          pattern: '''^([A-Za-z0-9\-\.]+\/){1}([A-Za-z0-9\-\.]+)[A-Za-z0-9\-\.\/]*$'''
          replacement: "${2}"
          result_key: "location"
        ....
    - strings:
        trim_prefix:
          field_key: "*"
          prefix: "points_"
        trim_suffix:
          field_key: "*"
          prefix: "_present_value"
```

**Expected output**:
```
[[processors.regex]]
    namepass = ["mqtt_consumer"]

  [[processors.regex.tags]]
    key = "topic"
    pattern = '''^([A-Za-z0-9\-\.]+\/){0}([A-Za-z0-9\-\.]+)[A-Za-z0-9\-\.\/]*$'''
    replacement = "${2}"
    result_key = "domain"

  [[processors.regex.tags]]
    key = "topic"
    pattern = '''^([A-Za-z0-9\-\.]+\/){1}([A-Za-z0-9\-\.]+)[A-Za-z0-9\-\.\/]*$'''
    replacement = "${2}"
    result_key = "location"
.....

[[processors.strings]]

  [[processors.strings.trim_prefix]]
    field_key = "*"
    prefix = "points_"

  [[processors.strings.trim_suffix]]
    field_key = "*"
    suffix = "_present_value"
```

**Actual output**:
```
[[processors.regex]]
  namepass = "mqtt_consumer"
  [[processors.regex.tags]]
    key = "topic"
    pattern = "'^([A-Za-z0-9\\-\\.]+\\/){4}([A-Za-z0-9\\-\\.]+)[A-Za-z0-9\\-\\.\\/]*$'"
    replacement = "${2}"
    result_key = "udmi_type"
[[processors.strings]]
  [[processors.strings.trim_prefix]]
    field_key = "*"
    prefix = "points_"
  [[processors.strings.trim_suffix]]
    field_key = "*"
    prefix = "_present_value"
```

There is only one `processors.regex.tags` block defined, being the last in the `values.yaml`, and I believe in the Helm interpolation is overwriting the blocks with a matching `tags` key.

**Is this a limitation/bug in the Helm charts, or with my yaml configuration in the `values.yaml`?**
